version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.839.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.27.0
    - 2.27.1
    - 2.28.0
    - 2.28.3
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.2
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.37.1
    - 2.37.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: dynamoose
    versions:
    - 2.5.0
    - 2.6.0
    - 2.7.0
    - 2.7.1
    - 2.7.2
